import { ThemeDefinition } from './themes';

export const THEME_DEFINITIONS: { [key in string]: ThemeDefinition } = {
    default: {
        SYNTAX_HIGHLIGHTING_THEME: 'dark-plus',

        COMMIT_COLOR: 'ffffff',
        COMMIT_SHA_COLOR: '00eeaa',
        COMMIT_AUTHOR_COLOR: '00aaee',
        COMMIT_DATE_COLOR: 'ffffff',

        FILE_NAME_COLOR: 'ffdd99',
        BORDER_COLOR: { color: 'ffdd9966', modifiers: ['dim'] },

        HUNK_HEADER_COLOR: { modifiers: ['dim'] },

        DELETED_WORD_COLOR: { color: '99000033', backgroundColor: 'cc000033' },
        INSERTED_WORD_COLOR: { color: '00990033', backgroundColor: '00cc0033' },

        DELETED_LINE_COLOR: { color: 'cc6666', backgroundColor: '3a3030' },
        INSERTED_LINE_COLOR: { color: '66cc66', backgroundColor: '303a30' },
        UNMODIFIED_LINE_COLOR: { color: 'ffffff' },
        MISSING_LINE_COLOR: {},

        DELETED_LINE_NO_COLOR: {
            color: '00000022',
            backgroundColor: '00000022',
        },
        INSERTED_LINE_NO_COLOR: {
            color: '00000022',
            backgroundColor: '00000022',
        },
        UNMODIFIED_LINE_NO_COLOR: { color: '666666' },
    },
    light: {
        SYNTAX_HIGHLIGHTING_THEME: 'light-plus',
        BORDER_COLOR: { color: 'cccccc', backgroundColor: 'eeeeee' },
        COMMIT_COLOR: { color: '333333', backgroundColor: 'eeeeee' },
        COMMIT_SHA_COLOR: { color: '006600' },
        COMMIT_AUTHOR_COLOR: { color: '663333' },
        COMMIT_DATE_COLOR: {},
        FILE_NAME_COLOR: { color: '336666', backgroundColor: 'eeeeee' },
        HUNK_HEADER_COLOR: { color: '666666', backgroundColor: 'e0e0e0' },
        DELETED_WORD_COLOR: { backgroundColor: 'eeaaaa' },
        INSERTED_WORD_COLOR: { backgroundColor: 'aaeeaa' },
        DELETED_LINE_COLOR: { color: '333333', backgroundColor: 'eecccc' },
        INSERTED_LINE_COLOR: { color: '333333', backgroundColor: 'cceecc' },
        DELETED_LINE_NO_COLOR: {
            color: 'ff000022',
            backgroundColor: '00000011',
        },
        INSERTED_LINE_NO_COLOR: {
            color: '00ff0022',
            backgroundColor: '00000011',
        },
        UNMODIFIED_LINE_COLOR: { color: '666666', backgroundColor: 'eeeeee' },
        UNMODIFIED_LINE_NO_COLOR: {
            color: 'ffffff88',
            backgroundColor: '00000008',
        },
        MISSING_LINE_COLOR: { backgroundColor: 'e8e8e8' },
    },
    'github-light': {
        SYNTAX_HIGHLIGHTING_THEME: 'github-light',
        BORDER_COLOR: { color: 'e1e4e8', backgroundColor: 'ffffff' },
        COMMIT_COLOR: { color: '05264c', backgroundColor: 'f1f8fe' },
        COMMIT_AUTHOR_COLOR: { color: '05264c', modifiers: ['bold'] },
        COMMIT_DATE_COLOR: { color: '05264c' },
        COMMIT_SHA_COLOR: {},
        FILE_NAME_COLOR: { color: '05264c', backgroundColor: 'ffffff' },
        HUNK_HEADER_COLOR: { color: '4c5154', backgroundColor: 'f1f8ff' },
        DELETED_WORD_COLOR: { backgroundColor: 'fdb8c0' },
        INSERTED_WORD_COLOR: { backgroundColor: 'acf2bd' },
        DELETED_LINE_COLOR: { color: '24292e', backgroundColor: 'ffeef0' },
        INSERTED_LINE_COLOR: { color: '24292e', backgroundColor: 'e6ffed' },
        UNMODIFIED_LINE_COLOR: { color: '6a737d', backgroundColor: 'ffffff' },
        MISSING_LINE_COLOR: { backgroundColor: 'fafbfc' },
        DELETED_LINE_NO_COLOR: { color: 'c2a9ad', backgroundColor: 'ffdce0' },
        INSERTED_LINE_NO_COLOR: { color: 'a5cfb0', backgroundColor: 'cdffd8' },
        UNMODIFIED_LINE_NO_COLOR: {
            color: 'd1d5da',
            backgroundColor: 'ffffff',
        },
    },
    'github-dark-dim': {
        SYNTAX_HIGHLIGHTING_THEME: 'github-dark',
        // DEFAULT_COLOR: { color: 'adbac7', backgroundColor: '22272e' },
        COMMIT_SHA_COLOR: { color: 'adbac7' },
        COMMIT_DATE_COLOR: { color: 'adbac7' },
        COMMIT_COLOR: { color: 'c6e6ff', backgroundColor: '22272e' },
        COMMIT_AUTHOR_COLOR: { modifiers: ['bold'] },
        BORDER_COLOR: { color: '444c56', backgroundColor: '22272e' },
        FILE_NAME_COLOR: { color: 'adbac7', backgroundColor: '22272e' },
        HUNK_HEADER_COLOR: { color: '768390', backgroundColor: '263441' },
        DELETED_WORD_COLOR: { backgroundColor: 'c93c3780' },
        INSERTED_WORD_COLOR: { backgroundColor: '46954a8c' },
        DELETED_LINE_COLOR: { backgroundColor: '442d30' },
        INSERTED_LINE_COLOR: { backgroundColor: '2a3c33' },
        UNMODIFIED_LINE_COLOR: { color: '768390', backgroundColor: '22282d' },
        MISSING_LINE_COLOR: { backgroundColor: '2d333b' },
        DELETED_LINE_NO_COLOR: { color: 'e5534b', backgroundColor: '442d30' },
        INSERTED_LINE_NO_COLOR: { color: '57ab5a', backgroundColor: '253230' },
        UNMODIFIED_LINE_NO_COLOR: { backgroundColor: '22282d' },
    },
};
